name: BaselineHPE
n_gpu: 1
dtype: float
target_dtype: float
arch:
  type: DeepPriorPPModel
  args:
    input_channels: 1
    pca_components: 30
    dropout_prob: 0.3
    train_mode: true
    init_w: true
data_loader:
  type: DepthJointsDataLoader
  args:
    data_dir: datasets/hand_pose_action
    dataset_type: train
    batch_size: 128
    pca_components: 30
    use_pca_cache: true
    num_workers: 8
    debug: false
    reduce: false
    preload_depth: false
    pca_overwrite_cache: true
    use_msra: true
    pca_size: 200000
    validation_split: 0.2
    shuffle: false
    randomise_params: true
    data_aug:
    - 0
    pca_data_aug:
    - 0
    use_orig_transformers: false
    use_orig_transformers_pca: false
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: false
loss: mse_loss
metrics:
- Avg3DError
lr_scheduler: null
trainer:
  epochs: 20
  save_dir: saved/
  save_period: 500
  verbosity: 2
  persistent_storage: false
  monitor: min val_avg_3d_err_mm
  early_stop: 5
  tensorboardX: true
  log_dir: logs
