name: BaselineHPE
n_gpu: 1
dtype: float
target_dtype: float


arch:
  type: DeepPriorPPModel
  args:
    input_channels: 1
    pca_components: 30
    dropout_prob: 0.3
    train_mode: true
    init_w: true


data_loader:
  type: DepthJointsDataLoader
  args:
    data_dir: datasets/hand_pose_action
    dataset_type: train
    batch_size: 128
    shuffle: true
    validation_split: -1.0
    pca_components: 30
    use_pca_cache: true
    num_workers: 8
    debug: false
    reduce: false
    preload_depth: false #true now this is not neede, after first epoch preloading is automatically done
    pca_overwrite_cache: false
    use_msra: false


optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
loss: mse_loss
metrics: [Avg3DError]
lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1


trainer:
  epochs: 50 # 10 #50
  save_dir: saved/
  save_period: 10 #2 #10
  verbosity: 2
  persistent_storage: false
  monitor: "min val_avg_3d_err_mm" #"min val_loss"
  early_stop: 20 #10 #20
  tensorboardX: true
  log_dir: logs
