name: BaselineLSTM
n_gpu: 1
dtype: float
target_dtype: long
arch:
  type: BaselineHARModel
  args:
    num_hidden_layers: 1
data_loader:
  type: JointsActionDataLoader
  args:
    data_dir: datasets/hand_pose_action
    dataset_type: train
    batch_size: 4
    shuffle: true
    validation_split: -1.0
    num_workers: 8
    debug: false
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
loss: nll_loss
metrics:
- top1_acc
- top3_acc
lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1
trainer:
  epochs: 100
  save_dir: saved/
  save_period: 5
  verbosity: 2
  persistent_storage: true
  monitor: max val_top1_acc
  early_stop: 30
  tensorboardX: true
  log_dir: logs
